#!/usr/bin/env node
/**
 * Copies published writing from the ../mi workspace into this repo.
 *
 * Writing is authored in ../mi, which also holds prompts, research and drafts
 * that have no business in a public site repo. This script pulls across only
 * the dated post files, so the site has a self-contained content/ directory
 * that builds without ../mi being present.
 *
 * Usage: pnpm sync-content
 */

import {
  readdirSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  copyFileSync,
  cpSync,
  existsSync,
  rmSync,
} from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const SOURCES = [
  {
    from: '../mi/personal-blog/content',
    to: 'content/blog',
    // images are served, so they go to public/ with their structure intact;
    // bodies reference them relatively and the reader rewrites the prefix
    images: 'public/writing/blog',
  },
  // newsletter posts stay canonical on Substack; mirrored here for the index
  {
    from: '../mi/the-working-prototype/content',
    to: 'content/newsletter',
    images: 'public/writing/newsletter',
  },
]

const IMAGE_DIRS = ['background-images', 'content-images']

/** dated post files only — page-*.md, prompts and assets stay behind */
const POST = /^\d{8}-[a-z0-9-]+\.md$/

let total = 0

for (const { from, to, images } of SOURCES) {
  const src = join(root, from)
  const dest = join(root, to)

  if (!existsSync(src)) {
    console.warn(`skip  ${from} — not found`)
    continue
  }

  // rebuild the directory so deletions upstream propagate
  rmSync(dest, { recursive: true, force: true })
  mkdirSync(dest, { recursive: true })

  const files = readdirSync(src).filter((f) => POST.test(f))
  for (const file of files) {
    copyFileSync(join(src, file), join(dest, file))
  }

  console.log(`sync  ${from} → ${to}  (${files.length} posts)`)
  total += files.length

  if (!images) continue
  const imageDest = join(root, images)
  rmSync(imageDest, { recursive: true, force: true })
  mkdirSync(imageDest, { recursive: true })

  for (const dir of IMAGE_DIRS) {
    const srcDir = join(src, dir)
    if (!existsSync(srcDir)) continue
    cpSync(srcDir, join(imageDest, dir), { recursive: true })
    console.log(`      ${dir}/`)
  }
}

// A light index the browser can import. The terminal commands need to list
// posts, and they are client-side, so they cannot read the filesystem.
function indexOf(dir, source) {
  const src = join(root, dir)
  if (!existsSync(src)) return []

  return readdirSync(src)
    .filter((f) => POST.test(f))
    .map((file) => {
      const raw = readFileSync(join(src, file), 'utf8')
      const meta = {}
      for (const line of raw.split('\n')) {
        if (!line.trim()) break
        const m = line.match(/^([A-Z][A-Za-z ]*):\s*(.*)$/)
        if (!m) break
        meta[m[1].toLowerCase()] = m[2].trim()
      }
      const [, y, mo, d, slug] = file.match(/^(\d{4})(\d{2})(\d{2})-(.+)\.md$/)

      // enough prose for search to be useful without shipping every post
      const body = raw
        .split('\n')
        .filter((l) => !/^[A-Z][A-Za-z ]*:/.test(l) && !/^-{3,}\s*$/.test(l))
        .join(' ')
        .replace(/<[^>]+>/g, ' ')
        .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
        .replace(/[#*_`>]/g, '')
        .replace(/\s+/g, ' ')
        .trim()

      return {
        source,
        slug,
        date: meta.date || `${y}-${mo}-${d}`,
        title: meta.title || slug.replace(/-/g, ' '),
        subtitle: meta.subtitle || undefined,
        excerpt: body.slice(0, 400),
      }
    })
    .sort((a, b) => b.date.localeCompare(a.date))
}

const index = [
  ...indexOf('../mi/personal-blog/content', 'blog'),
  ...indexOf('../mi/the-working-prototype/content', 'newsletter'),
]

writeFileSync(
  join(root, 'src/data/posts.ts'),
  `// Generated by \`pnpm sync-content\` — do not edit.
// A light index so client-side terminal commands can list posts.

export type PostRef = {
  source: 'blog' | 'newsletter'
  slug: string
  date: string
  title: string
  subtitle?: string
  excerpt: string
}

export const posts: PostRef[] = ${JSON.stringify(index, null, 2)}

export const blogPosts = posts.filter((p) => p.source === 'blog')
export const newsletterPosts = posts.filter((p) => p.source === 'newsletter')
`,
)
console.log(`index src/data/posts.ts  (${index.length} entries)`)

console.log(`done  ${total} posts`)
