// Generated by `pnpm sync-content` — do not edit.
// A light index so client-side terminal commands can list posts.

export type PostRef = {
  source: 'blog' | 'newsletter'
  slug: string
  date: string
  title: string
  subtitle?: string
}

export const posts: PostRef[] = [
  {
    "source": "blog",
    "slug": "teya-intro",
    "date": "2026-07-16",
    "title": "how and why i built a home ai assistant",
    "subtitle": "the AI was the easy part."
  },
  {
    "source": "blog",
    "slug": "riding-the-wave",
    "date": "2026-06-26",
    "title": "riding the wave"
  },
  {
    "source": "blog",
    "slug": "sorry-for-writing-so-late",
    "date": "2026-03-15",
    "title": "sorry for writing so late"
  },
  {
    "source": "blog",
    "slug": "economy-of-blame",
    "date": "2025-11-15",
    "title": "the economy of blame"
  },
  {
    "source": "blog",
    "slug": "prince-of-constraints",
    "date": "2025-11-03",
    "title": "prince of constraints"
  },
  {
    "source": "blog",
    "slug": "local-maxima",
    "date": "2025-10-27",
    "title": "local maxima"
  },
  {
    "source": "blog",
    "slug": "polyworking",
    "date": "2025-09-20",
    "title": "polyworking: why one job isn't enough anymore"
  },
  {
    "source": "blog",
    "slug": "loop-is-all-you-need",
    "date": "2025-06-29",
    "title": "a loop is all you need: building conversational ai agents"
  },
  {
    "source": "blog",
    "slug": "debugging-my-twenties",
    "date": "2025-06-10",
    "title": "debugging my twenties: that summer in france"
  },
  {
    "source": "blog",
    "slug": "writing-in-public",
    "date": "2025-06-08",
    "title": "writing in public: what i discovered during my 8-month writing break"
  },
  {
    "source": "blog",
    "slug": "is-education-broken",
    "date": "2024-09-29",
    "title": "my take on education and learning"
  },
  {
    "source": "blog",
    "slug": "sales-lessons",
    "date": "2024-04-22",
    "title": "learn to sell: b2b sales lessons from microsoft"
  },
  {
    "source": "blog",
    "slug": "why-sales-engineer",
    "date": "2024-02-15",
    "title": "why i started my tech career as a sales engineer @ microsoft"
  },
  {
    "source": "blog",
    "slug": "personal-website",
    "date": "2024-01-12",
    "title": "everyone should have a personal website"
  },
  {
    "source": "blog",
    "slug": "blog-better-than-cv",
    "date": "2023-12-12",
    "title": "how i got the data science interview with a cool scale-up without cv"
  },
  {
    "source": "newsletter",
    "slug": "what-kind-of-poker-player-is-an-ai",
    "date": "2026-07-13",
    "title": "what kind of poker player is an ai?",
    "subtitle": "a small, controlled experiment across models from OpenAI, Anthropic, and Mistral, run out of curiosity"
  },
  {
    "source": "newsletter",
    "slug": "context-solves-alignment",
    "date": "2026-06-28",
    "title": "context solves alignment?",
    "subtitle": "an agent is only as aligned as the context you give it"
  },
  {
    "source": "newsletter",
    "slug": "judgement-at-scale",
    "date": "2026-05-18",
    "title": "judgement at scale",
    "subtitle": "applying human judgement to every conversation without a human reading every one"
  },
  {
    "source": "newsletter",
    "slug": "how-to-do-agentic-evals",
    "date": "2026-04-09",
    "title": "how to do agentic evals",
    "subtitle": "what building an eval system for conversational agents actually required"
  },
  {
    "source": "newsletter",
    "slug": "build-for-reliability",
    "date": "2026-04-03",
    "title": "build for reliability",
    "subtitle": "why capable models still fail in production"
  },
  {
    "source": "newsletter",
    "slug": "the-legible-agent",
    "date": "2026-03-22",
    "title": "the legible agent",
    "subtitle": "if you can't trace your agent, you can't trust it"
  },
  {
    "source": "newsletter",
    "slug": "in-character",
    "date": "2026-03-15",
    "title": "in character",
    "subtitle": "does conversation history format affect how well an agent stays in role?"
  },
  {
    "source": "newsletter",
    "slug": "fixing-bias",
    "date": "2026-01-31",
    "title": "from finding bias to fixing it",
    "subtitle": "what data scientists knew before LLMs, and why it still applies"
  },
  {
    "source": "newsletter",
    "slug": "vulnerable-world-hypothesis",
    "date": "2025-11-16",
    "title": "the vulnerable world hypothesis",
    "subtitle": "and what happens if we flip it"
  },
  {
    "source": "newsletter",
    "slug": "why-this-newsletter",
    "date": "2025-11-15",
    "title": "why this newsletter exists",
    "subtitle": "for people building AI agents who care about getting them right"
  }
]

export const blogPosts = posts.filter((p) => p.source === 'blog')
export const newsletterPosts = posts.filter((p) => p.source === 'newsletter')
